SEED_QUERY = "elvis wiki discordant"
NUM_NODES = 3
SEED_ENGINE = "https://www.google.com/search?q="
THREAD_COUNT = 20
PAGE_LIMIT = 30000
BF_FALSE_POSITIVE_PROB = 0.02
MAX_PAGE_PER_DOMAIN = 50
TIMEOUT_LIMIT = 5
MODE_BFS_SEARCH = 0
MODE_PRIORITY_SEARCH = 1
COMMUNICAIOON_MODE_EXCHANGE = True
QUEUE_SIZE_LIMIT = 200000
CRAWLED_URLS_SIZE_LIMIT = 1000000
QUEUE_FILE_SIZE_LIMIT = 500000
QUEUE_MODE_TO_QUEUE = 0
QUEUE_MODE_TO_DISK = 1

SEARCH_MODE = MODE_BFS_SEARCH
PAGE_LIMIT_PER_NODE = int(PAGE_LIMIT / NUM_NODES)
